### ISSUE TITLE
Hardcoded paths properties should be moved to your local settings.xml

### ISSUE THREAD

**Issue by Phylock** [markiewb/readmeinprojectview#5]
To make it easier to clone an build your plugin, you should move configuration of absolute paths to software install on your own local machine to the settings.xml file.

An example of a settings entry.
```xml
<settings>
  <profiles>
   ...
    <profile>
      <id>netbeans-ide</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <netbeans.installation>d:/Program Files/NetBeans7.3/</netbeans.installation>
      </properties>
    </profile>
   ...
  </profiles>
</settings>
```

more info about [settings.xml](https://maven.apache.org/settings.html)

**Comment by markiewb** [comment]
Thank you for the report. You are correct. My settings.xml already included the netbeans.installation property. But the pom.xml of this project still included it. 
I removed the hardcoded paths and it still works.

BTW: If you like to have more project types supported, please open an issue or, even better, provide a pull request. It is not very difficult.
